# Generated by Django 3.2.4 on 2021-07-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='video',
            field=models.TextField(default='https://youtu.be/HAZJAzCshN4'),
            preserve_default=False,
        ),
    ]
