# Generated by Django 3.2.4 on 2021-10-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Materials', '0002_course_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Materials.materials')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Materials.comment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
