# Generated by Django 3.2.4 on 2021-10-16 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Materials', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
