# Generated by Django 3.2.4 on 2021-09-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materials', '0003_alter_materials_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='pdf',
            field=models.FileField(upload_to='materials_file'),
        ),
    ]
