# Generated by Django 3.2.4 on 2021-09-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materials', '0004_alter_materials_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
    ]
