# Generated by Django 3.2.4 on 2021-07-09 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HomePage', '0002_examfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='examfolder',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HomePage.courses'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examfolder',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
