# Generated by Django 3.2.5 on 2021-10-16 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HomePage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UncheckedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='files')),
                ('is_checked', models.BooleanField(default=False)),
                ('Marks', models.FloatField(default=0)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.courses')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.examfolder')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_no', models.CharField(max_length=100)),
                ('Marks', models.FloatField(default=0)),
                ('Script_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.uncheckedfile')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.examfolder')),
            ],
        ),
    ]
