# Generated by Django 3.2.5 on 2021-10-16 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_exams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptdetails',
            name='exam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.exams'),
        ),
        migrations.CreateModel(
            name='ExamScripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='Scripts/')),
                ('pdf_from_drive', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=100)),
                ('is_Checked', models.BooleanField(default=False)),
                ('Marks', models.FloatField(default=0)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.courses')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.exams')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='scriptdetails',
            name='Script_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.examscripts'),
        ),
    ]
