# Generated by Django 3.2.4 on 2021-07-09 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_auto_20210709_2032'),
        ('Exams', '0002_alter_uncheckedfile_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='uncheckedfile',
            name='Marks',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ScriptDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_no', models.CharField(max_length=100)),
                ('Marks', models.FloatField(default=0)),
                ('Script_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.uncheckedfile')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.examfolder')),
            ],
        ),
    ]
