# Generated by Django 3.2 on 2021-07-08 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_exams'),
        ('ExamScripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_no', models.CharField(max_length=100)),
                ('Marks', models.FloatField(default=0)),
                ('Script_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamScripts.examscripts')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.exams')),
            ],
        ),
    ]
