# Generated by Django 3.2.4 on 2021-08-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PdfConversion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handwrittenfiles',
            name='pdf',
            field=models.FileField(upload_to='handwrittenfiles'),
        ),
        migrations.AlterField(
            model_name='pdffiles',
            name='pdf',
            field=models.FileField(upload_to='pdffiles'),
        ),
    ]
