# Generated by Django 3.2.4 on 2021-09-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PdfComparison', '0002_auto_20210912_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='pdf1',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='history',
            name='pdf2',
            field=models.FileField(upload_to=''),
        ),
    ]
