# Generated by Django 3.2.4 on 2021-09-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PdfComparison', '0003_auto_20210912_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='pdf1',
            field=models.FileField(upload_to='compare_history'),
        ),
        migrations.AlterField(
            model_name='history',
            name='pdf2',
            field=models.FileField(upload_to='compare_history'),
        ),
    ]
