# Generated by Django 3.2.4 on 2021-10-14 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PdfComparison', '0006_uploaded_multiplefile1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_multiplefile1',
            name='pdf',
            field=models.FileField(upload_to='compare_multiplefile'),
        ),
        migrations.CreateModel(
            name='multiple_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf1', models.FileField(upload_to='compare_history')),
                ('pdf2', models.FileField(upload_to='compare_history')),
                ('rate', models.CharField(max_length=200)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
