# Generated by Django 3.2.4 on 2021-10-15 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PdfComparison', '0007_auto_20211015_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiple_history',
            name='pdf2_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PdfComparison.uploaded_multiplefile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multiple_history',
            name='pdf1',
            field=models.FileField(upload_to='compare_multiplehistory'),
        ),
        migrations.AlterField(
            model_name='multiple_history',
            name='pdf2',
            field=models.FileField(upload_to='compare_multiplehistory'),
        ),
    ]
