# Generated by Django 3.2.4 on 2021-10-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PdfComparison', '0008_auto_20211015_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiple_history',
            name='pdf1',
            field=models.FileField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='multiple_history',
            name='pdf2',
            field=models.FileField(upload_to='files'),
        ),
    ]
