# Generated by Django 3.2 on 2021-10-14 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GC_ExamScripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scriptID', models.CharField(max_length=200)),
                ('courseWorkID', models.CharField(max_length=200)),
                ('courseID', models.CharField(max_length=200)),
                ('student_id', models.CharField(max_length=100)),
                ('is_Checked', models.BooleanField(default=False)),
                ('Marks', models.FloatField(default=0)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GC_ScriptDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_no', models.CharField(max_length=100)),
                ('Marks', models.FloatField(default=0)),
                ('script', models.CharField(max_length=200)),
                ('Script_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoogleClassroom.gc_examscripts')),
            ],
        ),
    ]
